FROM tensorflow/tensorflow:1.12.0-gpu-py3

RUN apt-get update \
    && apt-get install -y libsm6 libxrender-dev libxext6

ADD $PWD/requirements-gpu.txt /requirements-gpu.txt
RUN pip3 install -r /requirements-gpu.txt

CMD ["/bin/bash"]